### ISSUE TITLE
Adding it to a CDN

### ISSUE THREAD

**Issue by chdanielmueller** [TerryMooreII/angular-azure-mobile-service#14]
Hi Terry,
I would like to ask you if you could publish this project to CDNJS. (Free Content Delivery Network)
https://github.com/cdnjs/cdnjs
Regards,
Daniel

**Comment by chdanielmueller** [comment]
Has been added to CDNJS with merge #4154
Can be added to your project using https://cdnjs.cloudflare.com/ajax/libs/angular-azure-mobile-service/1.3.2/angular-azure-mobile-service.min.js

Do you have time to update the Readme.md?

**Comment by TerryMooreII** [comment]
Thank you for taking care of this and updating the README file.   Can you send me instructions on how to update the cdn version if/when there are updates to this service?

**Comment by chdanielmueller** [comment]
The updating process should be automated when you add a new tag to the repo.

**Comment by TerryMooreII** [comment]
Ah cool, thanks
