### ISSUE TITLE
offline data sync

### ISSUE THREAD

**Issue by thomas-tran** [TerryMooreII/angular-azure-mobile-service#17]
I am just wondering whether offline feature and data synchronization will be included in next release?

Thomas

**Comment by TerryMooreII** [comment]
Can you send me links to some documentation about these features?  From what I can tell it looks like these features aren't part of the Javascript client.

**Comment by jonmiller1** [comment]
As far as I know the offline sync is a feature of the .NET client for azure mobile services.  So the code to make this work lives in the client library (which makes sense for offline mode, you can't make calls to azure without a connection).  Hopefully they will bring it to other client libraries in the future.

**Comment by thomas-tran** [comment]
You are right, I've checked azure mobile service document and they did not provide this feature for  java script client library.
