### ISSUE TITLE
oData queries

### ISSUE THREAD

**Issue by Chrillemeter** [TerryMooreII/angular-azure-mobile-service#26]
Is it possible to use oData queries with this?

**Comment by TerryMooreII** [comment]
Not direct odata queries but this service's query params pretty much line up with the windows mobiles service's odata parameters https://msdn.microsoft.com/en-us/library/azure/jj677199.aspx?f=255&MSPPError=-2147217396.

I am not sure that you can send direct odata queries to the window mobile service but if I'm wrong let me know and I will see how to incorporate that functionality into the service.

**Comment by Chrillemeter** [comment]
Hi again. Yes you can send odata queries direct like 
```javascript
userTable.read("$filter=username eq 'sven'");
```

You can read about this under the section "Execute an OData query operation".
http://azure.microsoft.com/sv-se/documentation/articles/mobile-services-html-how-to-use-client-library/

**Comment by TerryMooreII** [comment]
Oh, cool.  Thanks.  I will get this implemented.

**Comment by TerryMooreII** [comment]
So I lied, I already implemented this and didnt even know it.  You can use the .read() function to send odata queries to a specific table. 

```javascript
 Azureservice.read('test', "$filter=name eq 'Test User'")
                .then(function(data) {
                    console.log(data)
                }).catch(function(error) {
                    console.log(error)
                });
```

I will update the doc to reflect this
