### ISSUE TITLE
Custom Authentication setCurrentUser not passing X-ZUMO-AUTH request header query calls

### ISSUE THREAD

**Issue by kevindstanley1988** [TerryMooreII/angular-azure-mobile-service#27]
I am using custom authentication. My user object after I call my custom login api returns the below object.
user:{
  userId:'Custom:theUserId',
  authenticationToken:'theCrazyLongTokenHere'
}
I then call
AzureService.setCurrentUser(user);

I can get that object back by using AzureService.getCurrentUser() and that works so I know it is storing it, but whenever I make a call using query, getAll, or any authenticated api call I always get a 401 unauthorized. I know the authentication is working, I have used angular's 
$http({
  method:'GET',
  url:'https://mysite.azure-mobile.net/tables/myTable',
  headers:{
    'X-ZUMO-APPLICATION': 'API KEY HERE',
    'X-ZUMO-AUTH': 'theCrazyLongTokenHere'
  }
}).then(function(values){
  //values is completely full of values and i get a 200 ok return
});

When I use this service the X-ZUMO-AUTH header never gets added even when I have setCurrentUser.

**Comment by kevindstanley1988** [comment]
Sorry, I should have done some digging on my custom user object before I posted, for anyone elses information I fixed this by changing the user object like below.

user:{
userId:'Custom:theUserId',
mobileServiceAuthenticationToken:'theCrazyLongTokenHere'
}

**Comment by TerryMooreII** [comment]
Im glad that you were able to get it working and thanks for posting the fix for the next dev with that issue.
