### ISSUE TITLE
Is there a way to dynamically add extra where statements to the Azureservice.query? (criteria:)

### ISSUE THREAD

**Issue by courselogic** [TerryMooreII/angular-azure-mobile-service#30]
Using the azure mobile service client, we can add extra where statements to the query by adding more of the client.where({}). Is there a way that we can do it with this library? Thanks.

Here's the code I'm looking to implement that works with the mobile service sdk.

			if (list.parentId == null) {
				query.where({parentId: null});
			} else{
				query.where({parentId: list.parentId});
			}

**Comment by courselogic** [comment]
I figured it out. Since the criteria accepts an object, I just modified the object with all the properties that I needed and assigned each property accordingly. This is turning out to be a very flexible and great library. Thanks.

**Comment by TerryMooreII** [comment]
Sorry that I didnt get back to you sooner but I am glad that you figured it out.
