### ISSUE TITLE
Retrieving system properties

### ISSUE THREAD

**Issue by FreeWillaert** [TerryMooreII/angular-azure-mobile-service#32]
First, thanks for the great work!

I'd like to be able to retrieve system properties like __createdAt
As far as I see, this is currently not possible.

Fixed it for myself by changing getTable as follows:
...
**var data =** client.getTable(tableName);
**data.systemProperties = WindowsAzure.MobileServiceTable.SystemProperties.CreatedAt;**
return data;

Is there a better way? Or, could this be added as a feature?

**Comment by TerryMooreII** [comment]
I found a better way to do this:  Check out this blog post http://www.brandonmartinez.com/2014/10/22/retrieve-system-properties-in-azure-mobile-services-javascript-backend/ 

You add this to the scripts section for that table on the Azure management site.   Works like a champ.
Let me know if you need anything else.

**Comment by FreeWillaert** [comment]
Ah?
Thanks for that - I found that article but misunderstood and
tried something from the client - and that didn't work :o]
But indeed now I notice it says "in the Azure Mobile Services JavaScript
backend".

That should indeed solve my problem, so I'm alright, but you may wonder if
it should be the server or the client to decide which system properties...?

**Comment by TerryMooreII** [comment]
The only reason i can see MS doing this is so that you, the admin, has to specifically allow the client to see these internal properties.
