### ISSUE TITLE
404 error for Azure Mobile Service Client

### ISSUE THREAD

**Issue by alharding** [TerryMooreII/angular-azure-mobile-service#41]
Current link on README breaks:
* [Azure Mobile Service Client] (http://www.windowsazure.com/en-us/documentation/articles/mobile-services-html-get-started-data/)

This might be a better one:
* [Azure Mobile Service Client] (https://azure.microsoft.com/en-us/documentation/services/mobile-services/)

**Comment by TerryMooreII** [comment]
Fixed.  Thank you
